### ISSUE TITLE
TPC-H queries

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#47]
TPC-H is a set of queries to benchmark decision support on databases. The queries are business oriented.

This issue is an umbrella issue to group all the bugs that we need to fix to be able to run this set of queries.

## Bugs
- [x] #38 Support more than two tables on JOINS
- [x] #40 Unsupported syntax that should be supported
- [ ] #58 NOT REGEXP
## Missing features
- [x] #46 Aliased tables
- [ ] #45 DATE type
- [ ] #43 YEAR(date) function
- [ ] #42 SUBSTRING function
- [x] #41 Implement ParentExpr syntax
- [ ] #56 HAVING
- [ ] #57 INNER JOIN
- [ ] #59 SUBQUERY
- [ ] #60 List of values
- [ ] #61 AVG() function
- [ ] #62 Between

This issue will be updated with new needed features and bugs.
